// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCA8KMDqO3F24ofMmElsBfF0OOhpph-ZtU',
    appId: '1:964438341825:web:d07b9fe9fa69598f263c40',
    messagingSenderId: '964438341825',
    projectId: 'myfluttercollege-f1372',
    authDomain: 'myfluttercollege-f1372.firebaseapp.com',
    storageBucket: 'myfluttercollege-f1372.appspot.com',
    measurementId: 'G-JY8PCX4LRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOIFxiWUOHH5qn1d1zAki9SGMlu0eLbQk',
    appId: '1:964438341825:android:42c2b2d843b4a48c263c40',
    messagingSenderId: '964438341825',
    projectId: 'myfluttercollege-f1372',
    storageBucket: 'myfluttercollege-f1372.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFqRu_ARhfu-vimQ3WefhjVDzWaEcYGI4',
    appId: '1:964438341825:ios:6e7cfb5f8ae39985263c40',
    messagingSenderId: '964438341825',
    projectId: 'myfluttercollege-f1372',
    storageBucket: 'myfluttercollege-f1372.appspot.com',
    iosClientId: '964438341825-tomf821839n6b5t630ttgmaik5s9l2h4.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudOperation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFqRu_ARhfu-vimQ3WefhjVDzWaEcYGI4',
    appId: '1:964438341825:ios:d66466d072d64890263c40',
    messagingSenderId: '964438341825',
    projectId: 'myfluttercollege-f1372',
    storageBucket: 'myfluttercollege-f1372.appspot.com',
    iosClientId: '964438341825-h33d8pj97ps0h28e9i1kh9uppa6962ae.apps.googleusercontent.com',
    iosBundleId: 'com.example.crudOperation.RunnerTests',
  );
}
